CREATE TABLE [dbo].[Customer]
(
  [Id] INT IDENTITY(1, 1) NOT NULL CONSTRAINT [PK_Customer] PRIMARY KEY,
  [FirstName] NVARCHAR(100) NOT NULL,
  [LastName] NVARCHAR(100) NOT NULL,
  [Email] VARCHAR(320) NULL,
  [CreatedAtUtc] DATETIME2(3) NOT NULL CONSTRAINT [DF_Customer_CreatedAtUtc] DEFAULT (SYSUTCDATETIME())
)
